<?php load_theme_textdomain('percivale'); ?>
<?php
/*-----------------------------------------------------------------------------------*/
/*          Start Percivale Theme Functions - Please do not edit this file.          */
/*-----------------------------------------------------------------------------------*/

// Set path to theme specific functions
$functions_path = TEMPLATEPATH . '/functions/';
$widget_functions_path = TEMPLATEPATH . '/functions/widgets/';

require_once ($functions_path  . 'load-scripts.php'); // Load JS Goodies

// Other theme options
require_once ($functions_path . 'menus.php'); 		         // Menus
require_once ($functions_path . 'pagenavi.php'); 		     // Paging
require_once ($functions_path . 'breadcrumbs.php'); 		 // Breadcrumbs
require_once ($functions_path . 'sidebar-init.php'); 		 // Sidebar and footer widget areas
require_once ($functions_path . 'wptitle.php'); 		     // Title filter
require_once ($functions_path . 'theme-comments.php'); 		 // Custom comments
require_once ($functions_path . 'native.php'); 		         // Native Image Sizing
require_once ($functions_path . 'meta-box.php'); 		     // Meta Box
require_once ($functions_path . 'walker-nav.php');	         // Nav Sub titles
require_once ($functions_path . 'ui-labs/ui-labs.php');	     // UI Labs
require_once ($functions_path . 'updatenull.php');	         // Disable theme update checker

// Shortcodes
require_once ($functions_path . 'shortcodes/shortcodes.php'); 		     // Shortcodes
require_once ($functions_path . 'shortcodes/buttons-shortcode.php');	 // Button Shortcode
require_once ($functions_path . 'shortcodes/framed-box.php');	         // Framed Box Shortcode
require_once ($functions_path . 'shortcodes/tabs-toggle.php');	         // Tabs Toggle Shortcodes
require_once ($functions_path . 'shortcodes/service-boxes.php');	     // Service Boxes Shortcodes
require_once ($functions_path . 'shortcodes/pull-posts.php');	         // Recent Work Pull
require_once ($functions_path . 'shortcodes/action.php');	             // Action
require_once ($functions_path . 'shortcodes/contact-form.php');	         // Contact From
require_once ($functions_path . 'shortcodes/video-feature.php');	     // Framed video and feature
require_once ($functions_path . 'shortcodes/testimonials.php');	     // Testimonial Slider

// Include The Widgets
require_once ($widget_functions_path . 'widget-func.php');			                        // Twitter Javascript
require_once ($widget_functions_path . 'twitter-widget.php'); 		     					// Twitter
require_once ($widget_functions_path . 'flickr-widget.php'); 		     					// Flickr
require_once ($widget_functions_path . 'video-sidebar-widgets/video-sidebar-widgets.php'); 	// Video Widget
require_once ($widget_functions_path . 'popular-widget.php'); 		                        // Popular Widget
require_once ($widget_functions_path . 'posts-widget.php'); 		                        // Posts Widget

// DigiPanel Options Framework
require_once ($functions_path . 'digipanel/digipanel-func.php'); // DigiPanel Theme Options Framework

//Boring stuff
function homeblog_excerpt_length($length) {
	return 20;
}
add_filter('excerpt_length', 'homeblog_excerpt_length');

/**
 * Set the content width based on the theme's design and stylesheet.
 *
 * Used to set the width of images and content. Should be equal to the width the theme
 * is designed for, generally via the style.css stylesheet.
 */
if ( ! isset( $content_width ) )
	$content_width = 600;

// theme updates notification
//if ( is_admin() ) {
//    include_once (TEMPLATEPATH . '/functions/theme-updates/notify.php');
//}

// Add thumbnail support
// Since WP 2.9
if ( function_exists( 'add_theme_support' ) ) {
    add_theme_support( 'post-thumbnails' );
}

// Add default posts and comments RSS feed links to head
add_theme_support( 'automatic-feed-links' );

// custom background
add_custom_background();

// Make theme available for translation
// Translations can be filed in the /languages/ directory
load_theme_textdomain( TEMPLATEPATH . '/languages' );

$locale = get_locale();
$locale_file = TEMPLATEPATH . "/languages/$locale.php";
if ( is_readable( $locale_file ) )
	require_once( $locale_file );

/**
 * Remove inline styles printed when the gallery shortcode is used.
 * @return string The gallery style filter, with the styles themselves removed.
 */
function remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'remove_gallery_css' );

//remove formatter around shortcodes
function webtreats_formatter($content) {
	$new_content = '';

	/* Matches the contents and the open and closing tags */
	$pattern_full = '{(\[raw\].*?\[/raw\])}is';

	/* Matches just the contents */
	$pattern_contents = '{\[raw\](.*?)\[/raw\]}is';

	/* Divide content into pieces */
	$pieces = preg_split($pattern_full, $content, -1, PREG_SPLIT_DELIM_CAPTURE);

	/* Loop over pieces */
	foreach ($pieces as $piece) {
		/* Look for presence of the shortcode */
		if (preg_match($pattern_contents, $piece, $matches)) {

			/* Append to content (no formatting) */
			$new_content .= $matches[1];
		} else {

			/* Format and append to content */
			$new_content .= wptexturize(wpautop($piece));
		}
	}

	return $new_content;
}

// Remove the 2 main auto-formatters
remove_filter('the_content', 'wpautop');
remove_filter('the_content', 'wptexturize');

// Before displaying for viewing, apply this function
add_filter('the_content', 'webtreats_formatter', 99);
add_filter('widget_text', 'webtreats_formatter', 99);


?>